#line 1 "./frontend/scan.cc"

#line 3 "./frontend/scan.cc"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 98
#define YY_END_OF_BUFFER 99
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[299] =
    {   0,
        0,    0,   99,   97,   96,   96,   84,   97,   90,   83,
       97,   78,   79,   88,   87,   75,   86,   82,   89,   40,
       41,   76,   72,   91,   77,   92,   95,   38,   38,   80,
       81,   93,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   73,   94,   74,
       85,   71,    0,   49,    0,   57,   74,   66,   58,    0,
        0,   55,   63,   53,   64,   54,   65,    0,   44,    1,
        2,   56,   45,   40,    0,    0,   40,   40,    0,   40,
       41,   41,   41,   41,   81,   73,   80,   62,   68,   70,
       69,   61,   38,    0,    0,   59,   38,   38,   38,   38,

       38,   38,   38,   11,   38,   38,   38,   38,   38,   38,
       19,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   60,   67,   42,   50,    0,   44,    2,   44,
        0,   45,    0,   43,   40,   40,   40,   40,    0,   39,
       41,   41,   41,   41,   52,   51,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   17,   38,
       38,   21,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   38,   38,   38,    0,   44,
        0,   44,    0,   45,   43,   40,    0,    0,   39,    0,
       39,   39,   41,    3,    4,   38,    6,    7,   38,   38,

       38,   38,   13,   14,   38,   38,   18,   38,   22,   38,
       38,   38,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   35,   38,   38,    0,   44,    0,    0,    0,   39,
       39,    0,   46,   39,   39,    5,    8,   38,   38,   38,
       38,   16,   38,   38,   38,   38,   26,   38,   38,   38,
       38,   38,   38,   33,   38,   38,   37,    0,   47,    0,
        0,   48,   46,   39,   38,   38,   12,   15,   20,   38,
       38,   25,   27,   28,   29,   30,   31,   38,   38,   38,
       47,    0,   47,   48,   38,   10,   38,   38,   32,   38,
       38,   47,    9,   23,   24,   34,   36,    0

    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   28,
       29,   29,   29,   29,   29,   30,   29,   29,   29,   31,
       29,   29,   29,   29,   32,   29,   29,   33,   29,   29,
       34,   35,   36,   37,   29,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   29,   47,   48,   49,   50,
       51,   52,   29,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,   65,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[66] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    4,    1,    5,    5,    5,    1,
        1,    1,    1,    1,    1,    5,    5,    5,    6,    6,
        7,    6,    6,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    6,    6,    6,    6,    6,    6,    6,
        6,    7,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[306] =
    {   0,
        0,    0,  502,  503,  503,  503,  478,   61,   44,   62,
      465,  503,  503,  476,   58,  503,   59,   57,   68,   82,
      127,  474,  503,   72,  474,   63,  503,    0,   72,  503,
      503,  473,  439,   37,   60,   51,   58,   56,  443,   60,
      442,  450,   73,  431,  440,  438,  443,  503,   66,  503,
      503,  503,  108,  503,    0,  503,  503,  503,  503,  112,
      479,  503,  503,  503,  503,  503,  503,  471,  134,  503,
        0,  503,  161,   89,  108,  153,  102,   91,  470,  136,
        0,  155,  107,  142,  503,  503,  503,  461,  503,  503,
      503,  460,    0,  128,  447,  503,  426,  429,  437,  424,

      439,  426,  432,  418,  419,  416,  416,  419,  416,  413,
        0,  101,  417,  142,  415,  149,  128,  419,  412,  148,
      153,  417,  503,  503,  503,  503,  200,  503,    0,  203,
      220,  503,  188,  224,   84,  503,  432,  413,    0,  225,
      104,  503,  430,  411,  503,  503,  407,  409,  418,  413,
      401,  161,  415,  413,  409,  401,  407,  410,    0,  396,
      400,    0,  401,  398,  388,  386,  388,  390,  397,  383,
      381,  381,  393,  383,  387,  391,  393,  382,  206,  231,
      246,  503,  209,  252,  503,  503,  177,  216,  246,  271,
      165,  243,  503,    0,    0,  382,    0,    0,  373,  381,

      370,  377,    0,    0,  370,  359,    0,  355,    0,  350,
      344,  341,  338,  350,  340,  343,  348,  347,  345,  335,
      340,    0,  328,  340,  275,  279,  294,  235,  302,  230,
      503,  286,  306,  350,  331,    0,    0,  328,  326,  331,
      322,    0,  329,  315,  323,  318,    0,  326,  313,  315,
      298,  300,  298,    0,  285,  280,    0,  311,  314,  329,
      320,  333,  503,  503,  262,  262,    0,    0,    0,  273,
      270,    0,    0,    0,    0,    0,    0,  258,  242,  205,
      503,  341,  347,  503,  202,    0,  183,  180,    0,  159,
      131,  503,    0,    0,    0,    0,    0,  503,  395,  402,

      405,  412,  416,   66,  417
    } ;

static const flex_int16_t yy_def[306] =
    {   0,
      298,    1,  298,  298,  298,  298,  298,  299,  298,  298,
      300,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  301,  301,  298,
      298,  298,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  298,  298,  298,
      298,  298,  299,  298,  299,  298,  298,  298,  298,  300,
      300,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      302,  298,  298,   20,  298,  298,  298,  298,  303,  298,
       21,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  301,  299,  300,  298,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  298,  298,  298,  298,  298,  298,  302,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  304,  303,
      298,  298,  298,  298,  298,  298,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  298,  298,
      298,  298,  298,  298,  298,  298,  304,  305,  298,  298,
      298,  298,  298,  301,  301,  301,  301,  301,  301,  301,

      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  298,  298,  298,  305,  298,  298,
      298,  298,  298,  298,  298,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  298,  298,  298,
      298,  298,  298,  298,  301,  301,  301,  301,  301,  301,
      301,  301,  301,  301,  301,  301,  301,  301,  301,  301,
      298,  298,  298,  298,  301,  301,  301,  301,  301,  301,
      301,  298,  301,  301,  301,  301,  301,    0,  298,  298,

      298,  298,  298,  298,  298
    } ;

static const flex_int16_t yy_nxt[569] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   22,
       23,   24,   25,   26,   27,   28,   28,   28,   28,   29,
       28,   28,   28,   30,    4,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   28,   40,   28,   41,   28,   28,
       28,   28,   42,   43,   44,   45,   46,   47,   28,   28,
       28,   48,   49,   50,   51,   54,   56,   57,   58,   63,
      187,   68,   65,   69,   69,   69,   94,   86,   70,   95,
       64,   66,   67,   71,   59,   91,   92,   98,  123,   99,
       72,   87,  103,   88,   89,   55,   73,  100,   74,   74,

       75,  104,  111,  108,  101,  105,  109,  106,   76,  112,
      102,   77,   54,   78,   79,  136,  107,  115,  116,  125,
      137,  298,   73,   76,   75,   75,   75,  117,  124,   80,
      118,  135,   54,  136,   76,  142,  143,   78,  138,  136,
       79,   73,   55,   81,   81,   81,   61,  298,  161,   76,
       69,   69,   69,   76,  144,  162,   82,  136,   83,  142,
      127,  128,   55,  128,  133,  170,  133,  136,   76,  134,
      134,  134,  297,  142,   84,  127,  128,  130,  130,  130,
      171,  128,   83,  135,  141,  164,  142,  131,  132,  141,
      132,  136,  168,  174,  234,  165,  166,  142,  176,  296,

      177,  175,  131,  132,  134,  134,  134,  227,  132,  169,
      142,  179,  235,  179,  199,  200,  180,  180,  180,  130,
      130,  130,  180,  180,  180,  184,  184,  184,  227,  181,
      182,  183,  182,  183,  295,  294,  184,  184,  184,  188,
      134,  134,  134,  293,  181,  182,  229,  180,  180,  180,
      182,  185,  291,  185,  189,  190,  191,  225,  128,  225,
      128,  231,  226,  226,  226,  260,  185,  229,  184,  184,
      184,  185,  192,  128,  231,  230,  190,  231,  128,  132,
      191,  132,  232,  290,  232,  231,  260,  233,  233,  233,
      230,  226,  226,  226,  132,  226,  226,  226,  231,  132,

      289,  231,  233,  233,  233,  258,  182,  258,  182,  288,
      259,  259,  259,  261,  287,  261,  286,  285,  262,  262,
      262,  182,  233,  233,  233,  280,  182,  259,  259,  259,
      259,  259,  259,  263,  279,  263,  262,  262,  262,  278,
      282,  281,  282,  281,  277,  283,  283,  283,  263,  262,
      262,  262,  276,  263,  275,  274,  281,  283,  283,  283,
      284,  281,  284,  283,  283,  283,  273,  272,  271,  270,
      269,  268,  267,  266,  292,  284,  292,  265,  264,  264,
      284,  257,  256,  255,  254,  253,  252,  251,  250,  292,
      249,  248,  247,  246,  292,   53,  245,   53,   53,   53,

       53,   53,   60,  244,  243,   60,   60,   60,   60,   93,
       93,   93,  129,  242,  129,  129,  129,  129,  129,  140,
      140,  228,  241,  228,  240,  239,  238,  237,  236,  224,
      223,  222,  221,  220,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  207,  206,  205,  204,
      203,  202,  201,  198,  197,  196,  195,  194,  193,  193,
      186,  186,  178,  173,  172,  167,  163,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  149,  148,
      147,   61,  146,  145,  139,  126,   60,  122,  121,  120,
      119,  114,  113,  110,   97,   96,   90,   85,   62,   61,

       52,  298,    3,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298
    } ;

static const flex_int16_t yy_chk[569] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,    9,    9,   10,   15,
      304,   18,   17,   18,   18,   18,   29,   24,   19,   29,
       15,   17,   17,   19,   10,   26,   26,   34,   49,   34,
       19,   24,   36,   24,   24,    8,   20,   35,   20,   20,

       20,   36,   40,   38,   35,   37,   38,   37,   20,   40,
       35,   20,   53,   20,   20,  135,   37,   43,   43,   60,
       78,   74,   75,   20,   75,   75,   75,   43,   49,   20,
       43,   77,   94,   77,   75,  141,   83,   20,   78,  135,
       20,   21,   53,   21,   21,   21,   60,   74,  112,   75,
       69,   69,   69,   21,   83,  112,   21,   77,   21,  141,
       69,   69,   94,   69,   76,  117,   76,   80,   21,   76,
       76,   76,  291,   84,   21,   69,   69,   73,   73,   73,
      117,   69,   21,   80,   82,  114,   82,   73,   73,   84,
       73,   80,  116,  120,  191,  114,  114,   84,  121,  290,

      121,  120,   73,   73,  133,  133,  133,  187,   73,  116,
       82,  127,  191,  127,  152,  152,  127,  127,  127,  130,
      130,  130,  179,  179,  179,  183,  183,  183,  187,  130,
      130,  131,  130,  131,  288,  287,  131,  131,  131,  140,
      134,  134,  134,  285,  130,  130,  188,  180,  180,  180,
      130,  134,  280,  134,  140,  140,  140,  181,  180,  181,
      180,  230,  181,  181,  181,  228,  134,  188,  184,  184,
      184,  134,  140,  180,  192,  189,  140,  189,  180,  184,
      140,  184,  190,  279,  190,  230,  228,  190,  190,  190,
      192,  225,  225,  225,  184,  226,  226,  226,  192,  184,

      278,  189,  232,  232,  232,  227,  226,  227,  226,  271,
      227,  227,  227,  229,  270,  229,  266,  265,  229,  229,
      229,  226,  233,  233,  233,  256,  226,  258,  258,  258,
      259,  259,  259,  233,  255,  233,  261,  261,  261,  253,
      260,  259,  260,  259,  252,  260,  260,  260,  233,  262,
      262,  262,  251,  233,  250,  249,  259,  282,  282,  282,
      262,  259,  262,  283,  283,  283,  248,  246,  245,  244,
      243,  241,  240,  239,  283,  262,  283,  238,  235,  234,
      262,  224,  223,  221,  220,  219,  218,  217,  216,  283,
      215,  214,  213,  212,  283,  299,  211,  299,  299,  299,

      299,  299,  300,  210,  208,  300,  300,  300,  300,  301,
      301,  301,  302,  206,  302,  302,  302,  302,  302,  303,
      303,  305,  205,  305,  202,  201,  200,  199,  196,  178,
      177,  176,  175,  174,  173,  172,  171,  170,  169,  168,
      167,  166,  165,  164,  163,  161,  160,  158,  157,  156,
      155,  154,  153,  151,  150,  149,  148,  147,  144,  143,
      138,  137,  122,  119,  118,  115,  113,  110,  109,  108,
      107,  106,  105,  104,  103,  102,  101,  100,   99,   98,
       97,   95,   92,   88,   79,   68,   61,   47,   46,   45,
       44,   42,   41,   39,   33,   32,   25,   22,   14,   11,

        7,    3,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298,  298,  298,
      298,  298,  298,  298,  298,  298,  298,  298
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "./frontend/c.l"
#line 10 "./frontend/c.l"
#include <cstdio>
#include <iostream>
#include "parse.hh"
#include "front_env.h"
#include "juicyc/symbol.h"

using namespace juicyc;

int line = 0;
int column = 0;
uint16_t file = 0;

// hook scanner input to
// customized preprocessor.
// At most one line once, good for resetting
// file and line number. 
#define YY_INPUT(buf, result, max_size)  \
  result = 0; \
  while (1) { \
    int c = FrontEnv::pp->get(); \
    if (FrontEnv::pp->eof()) { \
      break; \
    } \
    buf[result++] = c; \
    if (result == max_size || c == '\n') { \
      break; \
    } \
  }

#define MAKE_TOKEN(token) \
  Terminal* tmp = new Terminal(); \
  yylval.sym = tmp; \
  tmp->value = yytext; \
  tmp->type = token; \
  tmp->file = file; \
  tmp->line = line; \
  tmp->col = column; \
  return token;


void count(void);
void comment(void);
int check_type(void);
#line 711 "./frontend/scan.cc"
/* if to use original flex on Windows,
 * please add following options:
 * %option nounistd
 * %option never-interactive
 * by Tabokie
 */
#line 718 "./frontend/scan.cc"

#define INITIAL 0

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 62 "./frontend/c.l"

#line 934 "./frontend/scan.cc"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 299 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 503 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "./frontend/c.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "./frontend/c.l"
{ /* consume //-comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 67 "./frontend/c.l"
{ count(); MAKE_TOKEN(AUTO) }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 68 "./frontend/c.l"
{ count(); MAKE_TOKEN(TOKEN_BOOL) }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 69 "./frontend/c.l"
{ count(); MAKE_TOKEN(BREAK) }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 70 "./frontend/c.l"
{ count(); MAKE_TOKEN(CASE) }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 71 "./frontend/c.l"
{ count(); MAKE_TOKEN(TOKEN_CHAR) }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 72 "./frontend/c.l"
{ count(); MAKE_TOKEN(TOKEN_CONST) }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 73 "./frontend/c.l"
{ count(); MAKE_TOKEN(CONTINUE) }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 74 "./frontend/c.l"
{ count(); MAKE_TOKEN(DEFAULT) }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 75 "./frontend/c.l"
{ count(); MAKE_TOKEN(DO) }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "./frontend/c.l"
{ count(); MAKE_TOKEN(TOKEN_DOUBLE) }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 77 "./frontend/c.l"
{ count(); MAKE_TOKEN(ELSE) }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "./frontend/c.l"
{ count(); MAKE_TOKEN(ENUM) }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 79 "./frontend/c.l"
{ count(); MAKE_TOKEN(EXTERN) }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 80 "./frontend/c.l"
{ count(); MAKE_TOKEN(TOKEN_FLOAT) }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 81 "./frontend/c.l"
{ count(); MAKE_TOKEN(FOR) }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 82 "./frontend/c.l"
{ count(); MAKE_TOKEN(GOTO) }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 83 "./frontend/c.l"
{ count(); MAKE_TOKEN(IF) }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 84 "./frontend/c.l"
{ count(); MAKE_TOKEN(INLINE) }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 85 "./frontend/c.l"
{ count(); MAKE_TOKEN(TOKEN_INT) }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 86 "./frontend/c.l"
{ count(); MAKE_TOKEN(TOKEN_LONG) }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 87 "./frontend/c.l"
{ count(); MAKE_TOKEN(REGISTER) }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 88 "./frontend/c.l"
{ count(); MAKE_TOKEN(RESTRICT) }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 89 "./frontend/c.l"
{ count(); MAKE_TOKEN(RETURN) }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 90 "./frontend/c.l"
{ count(); MAKE_TOKEN(TOKEN_SHORT) }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 91 "./frontend/c.l"
{ count(); MAKE_TOKEN(TOKEN_SIGNED) }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 92 "./frontend/c.l"
{ count(); MAKE_TOKEN(SIZEOF) }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 93 "./frontend/c.l"
{ count(); MAKE_TOKEN(STATIC) }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 94 "./frontend/c.l"
{ count(); MAKE_TOKEN(STRUCT) }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 95 "./frontend/c.l"
{ count(); MAKE_TOKEN(SWITCH) }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 96 "./frontend/c.l"
{ count(); MAKE_TOKEN(TYPEDEF) }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 97 "./frontend/c.l"
{ count(); MAKE_TOKEN(UNION) }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 98 "./frontend/c.l"
{ count(); MAKE_TOKEN(TOKEN_UNSIGNED) }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 99 "./frontend/c.l"
{ count(); MAKE_TOKEN(TOKEN_VOID) }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 100 "./frontend/c.l"
{ count(); MAKE_TOKEN(VOLATILE) }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 101 "./frontend/c.l"
{ count(); MAKE_TOKEN(WHILE) }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 103 "./frontend/c.l"
{ count(); MAKE_TOKEN(check_type()) }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 105 "./frontend/c.l"
{ count(); MAKE_TOKEN(CONSTANT) }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 106 "./frontend/c.l"
{ count(); MAKE_TOKEN(CONSTANT) }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 107 "./frontend/c.l"
{ count(); MAKE_TOKEN(CONSTANT) }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 108 "./frontend/c.l"
{ count(); MAKE_TOKEN(CONSTANT) }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 110 "./frontend/c.l"
{ count(); MAKE_TOKEN(CONSTANT) }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 111 "./frontend/c.l"
{ count(); MAKE_TOKEN(CONSTANT) }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 112 "./frontend/c.l"
{ count(); MAKE_TOKEN(CONSTANT) }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 113 "./frontend/c.l"
{ count(); MAKE_TOKEN(CONSTANT) }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 114 "./frontend/c.l"
{ count(); MAKE_TOKEN(CONSTANT) }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 115 "./frontend/c.l"
{ count(); MAKE_TOKEN(CONSTANT) }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 118 "./frontend/c.l"
{ count(); MAKE_TOKEN(STRING_LITERAL) }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 120 "./frontend/c.l"
{ count(); MAKE_TOKEN(ELLIPSIS) }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 121 "./frontend/c.l"
{ count(); MAKE_TOKEN(RIGHT_ASSIGN) }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 122 "./frontend/c.l"
{ count(); MAKE_TOKEN(LEFT_ASSIGN) }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 123 "./frontend/c.l"
{ count(); MAKE_TOKEN(ADD_ASSIGN) }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 124 "./frontend/c.l"
{ count(); MAKE_TOKEN(SUB_ASSIGN) }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 125 "./frontend/c.l"
{ count(); MAKE_TOKEN(MUL_ASSIGN) }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 126 "./frontend/c.l"
{ count(); MAKE_TOKEN(DIV_ASSIGN) }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 127 "./frontend/c.l"
{ count(); MAKE_TOKEN(MOD_ASSIGN) }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 128 "./frontend/c.l"
{ count(); MAKE_TOKEN(AND_ASSIGN) }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 129 "./frontend/c.l"
{ count(); MAKE_TOKEN(XOR_ASSIGN) }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 130 "./frontend/c.l"
{ count(); MAKE_TOKEN(OR_ASSIGN) }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 131 "./frontend/c.l"
{ count(); MAKE_TOKEN(RIGHT_OP) }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 132 "./frontend/c.l"
{ count(); MAKE_TOKEN(LEFT_OP) }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 133 "./frontend/c.l"
{ count(); MAKE_TOKEN(INC_OP) }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 134 "./frontend/c.l"
{ count(); MAKE_TOKEN(DEC_OP) }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 135 "./frontend/c.l"
{ count(); MAKE_TOKEN(PTR_OP) }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 136 "./frontend/c.l"
{ count(); MAKE_TOKEN(AND_OP) }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 137 "./frontend/c.l"
{ count(); MAKE_TOKEN(OR_OP) }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 138 "./frontend/c.l"
{ count(); MAKE_TOKEN(LE_OP) }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 139 "./frontend/c.l"
{ count(); MAKE_TOKEN(GE_OP) }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 140 "./frontend/c.l"
{ count(); MAKE_TOKEN(EQ_OP) }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 141 "./frontend/c.l"
{ count(); MAKE_TOKEN(NE_OP) }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 142 "./frontend/c.l"
{ count(); MAKE_TOKEN(';') }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 143 "./frontend/c.l"
{ count(); MAKE_TOKEN('{') }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 144 "./frontend/c.l"
{ count(); MAKE_TOKEN('}') }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 145 "./frontend/c.l"
{ count(); MAKE_TOKEN(',') }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 146 "./frontend/c.l"
{ count(); MAKE_TOKEN(':') }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 147 "./frontend/c.l"
{ count(); MAKE_TOKEN('=') }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 148 "./frontend/c.l"
{ count(); MAKE_TOKEN('(') }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 149 "./frontend/c.l"
{ count(); MAKE_TOKEN(')') }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 150 "./frontend/c.l"
{ count(); MAKE_TOKEN('[') }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 151 "./frontend/c.l"
{ count(); MAKE_TOKEN(']') }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 152 "./frontend/c.l"
{ count(); MAKE_TOKEN('.') }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 153 "./frontend/c.l"
{ count(); MAKE_TOKEN('&') }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 154 "./frontend/c.l"
{ count(); MAKE_TOKEN('!') }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 155 "./frontend/c.l"
{ count(); MAKE_TOKEN('~') }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 156 "./frontend/c.l"
{ count(); MAKE_TOKEN('-') }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 157 "./frontend/c.l"
{ count(); MAKE_TOKEN('+') }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 158 "./frontend/c.l"
{ count(); MAKE_TOKEN('*') }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 159 "./frontend/c.l"
{ count(); MAKE_TOKEN('/') }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 160 "./frontend/c.l"
{ count(); MAKE_TOKEN('%') }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 161 "./frontend/c.l"
{ count(); MAKE_TOKEN('<') }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 162 "./frontend/c.l"
{ count(); MAKE_TOKEN('>') }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 163 "./frontend/c.l"
{ count(); MAKE_TOKEN('^') }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 164 "./frontend/c.l"
{ count(); MAKE_TOKEN('|') }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 165 "./frontend/c.l"
{ count(); MAKE_TOKEN('?') }
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 167 "./frontend/c.l"
{ count(); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 168 "./frontend/c.l"
{ /* Add code to complain about unmatched characters */ }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 170 "./frontend/c.l"
ECHO;
	YY_BREAK
#line 1482 "./frontend/scan.cc"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 299 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 299 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 298);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 170 "./frontend/c.l"


int yywrap(void)
{
    return 1;
}


void comment(void)
{
    // char c, prev = 0;
  
    // while ((c = input()) != 0)      /* (EOF maps to 0) */
    // {
    //     if (c == '/' && prev == '*')
    //         return;
    //     prev = c;
    // }
    // yyerror("unterminated comment");
}

// called by preprocessor

void set_count(int l, int c) {
  line = l;
  column = c;
}

void set_file(int f) {
  file = f;
}

void count(void)
{
  int i;
  for (i = 0; yytext[i] != '\0'; i++)
    if (yytext[i] == '\n') {
      line ++;
      column = 0;
    }
    else if (yytext[i] == '\t')
      column += 8 - (column % 8);
    else
      column++;
}


int check_type(void)
{
/*
* pseudo code --- this is what it should check
*
*   if (yytext == type_name)
*       return TYPE_NAME;
*
*   return IDENTIFIER;
*/

/*
*   it actually will only return IDENTIFIER
*/

    return IDENTIFIER;
}
